// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeAspNetCoreWithKunvenkat.Models;

namespace PracticeAspNetCoreWithKunvenkat.Migrations
{
    [DbContext(typeof(AppDbContex))]
    [Migration("20211029092315_withMoreDataRepear")]
    partial class withMoreDataRepear
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeAspNetCoreWithKunvenkat.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "Tedu@abv.bg",
                            Name = "Tedu"
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "Radu@abv.bg",
                            Name = "Radu"
                        },
                        new
                        {
                            Id = 3,
                            Department = 3,
                            Email = "Boju@abv.bg",
                            Name = "Boju"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
